version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: go run main.go -b 0.0.0.0
    depends_on:
      - db

volumes:
  postgres-db: